spring:
  profiles:
    active: ${profile}

springdoc:
  swagger-ui:
    path: /swagger # ??? ?? ??
    groups-order: DESC # API ?? ?? ??
    tags-sorter: alpha # ?? ?? ??.
    operationsSorter: method # ???? ?? ??
    disable-swagger-default-url: true # swagger-ui default url? petstore html? ???? ??
    display-request-duration: true
  api-docs:
    path: /api-docs # openAPI ?? ??. default ?? /v3/api-docs ??.
  show-actuator: true # Spring Actuator? endpoint?? ??? ????
  default-consumes-media-type: application/json # request media type ? ?? ?
  default-produces-media-type: application/json # response media type ? ?? ?
  paths-to-match: /** # ?? ??? ???? controller? swagger-ui? ????.